### ISSUE TITLE
[iOS] Build Failed

### ISSUE THREAD

**Issue by aprct** [GantMan/jail-monkey#1]
Hey,

I'm getting a "Build Failed" when trying to run this on a simulator after I link the libJailMonkey.a library to the build target in XCode.

It doesn't give me an error message or anything. It just tells me that the build has failed. Any ideas?

**Comment by aprct** [comment]
Figured it out. 
2 issues in JailMonkey.m:

1.  Need to import UIKit because it is a dependency of UIApplication
2. Missing semicolon on line 46 :)

Will submit a PR.

**Comment by GantMan** [comment]
Released 0.0.5 and verified it works!
