### ISSUE TITLE
Android False Positives

### ISSUE THREAD

**Issue by gustavjf** [GantMan/jail-monkey#12]
I've just installed and linked the library and called `JailMonkey.isJailBroken()` in `componentDidMount()` of my top-level component. I got three false positives on separate physical devices:

- Android 6.0.1 (rooted once, now no longer rooted)
- Android 7.0 (never rooted)
- Android O (never rooted)

Does this library not yet support 6.X and above?

**Comment by GantMan** [comment]
I'm happy to update the code.  I'm currently unaware of what the prescribed detection methods are for those versions, but if you would be so kind as to link me to any docs/stackoverflows for each version, I'll implement the code.  

Additionally this is a difficult thing to test (# of devices and all) so help appreciated there as well.  

I'd like this library to remain active.  Let's get those updates in place!

**Comment by gustavjf** [comment]
Thanks for the quick response.

I'm also completely unaware of the current methods, but FWIW, https://github.com/beast/react-native-isDeviceRooted worked for the devices I mentioned above. Still struggling with iOS compilation so I can't comment on that, but Android seems to be working as expected.

This seems to be the relevant file: https://github.com/beast/react-native-isDeviceRooted/blob/master/android/app/src/main/java/my/fin/RNIsDeviceRootedModule.java

**Comment by gustavjf** [comment]
Happy to test again on these devices if you need some help with that.

**Comment by GantMan** [comment]
Thanks @gustavjf - I will review `isDeviceRooted` and report back!

**Comment by gustavjf** [comment]
Awesome, thank you!

**Comment by gustavjf** [comment]
If there's anything else I can do to help other than test on physical devices, let me know. I'd look into preparing a PR but my Java chops are non-existent.

**Comment by GantMan** [comment]
@gustavjf - can you test this branch please?

https://github.com/GantMan/jail-monkey/tree/fix_android

**Comment by gustavjf** [comment]
Just tested this after adding a missing import for `BufferedReader` class and all three non-rooted devices I listed above return `false` as expected. Emulators also return `true` as expected.

As is, it won't compile because of that missing import though.

Thank you for digging into this!

**Comment by GantMan** [comment]
Sorry for the wait, it's been a busy week.
New version published to npm `0.0.8`
