### ISSUE TITLE
JailMonkey.canMockLocation() return false in physical device (Android and Ios) and Ios Emulator return True

### ISSUE THREAD

**Issue by moisesgibson14** [GantMan/jail-monkey#154]
Hello, I have the problem that when using the 
"jail-monkey" library: "^2.7.0" 
on physical devices when using JailMonkey.canMockLocation() it returns false but when I try in the ios emulator it returns true, 
I would like to know if there is something additional that I must do since in both physical devices you are adding a false location

const mockLocation = await JailMonkey.canMockLocation();
mockLocation return False! 

I'm Using FakeGps to Android and in Ios through the computer I change the location of the iphone

**Comment by Sulaiman122** [comment]
same issue
ios simulator return true, but in real ios device return false after simulating location from xcode

**Comment by manouareY** [comment]
same here
