### ISSUE TITLE
Update to React-native 0.47.0 for Android

### ISSUE THREAD

**Issue by florismettey** [GantMan/jail-monkey#16]
React-native v0.47.0 had a breaking change for Android and we can't use jail-monkey with React v0.47.0. In order to fix it, we need to remove `createJSModules` from `JailMonkeyPackage.java`
I saw you merged it for an other project here https://github.com/rebeccahughes/react-native-device-info/pull/191/files.
I would like to do a pull request to fix it but I don't have the rights

**Comment by GantMan** [comment]
you can do a PR!  Or if you'd like I'll do it.  But you shouldn't have any issues doing a PR.

**Comment by dacarley** [comment]
I've submitted a PR for this change.  https://github.com/GantMan/jail-monkey/pull/17

**Comment by GantMan** [comment]
closed via #17
