### ISSUE TITLE
Android false positive caused by checking for presence of `test-keys` build tag

### ISSUE THREAD

**Issue by gustavjf** [GantMan/jail-monkey#18]
I've come across another false positive related to the root detection method that checks for the presence of `'test-keys'` [here](https://github.com/GantMan/jail-monkey/blob/898b83cedd23810577c4f7dad842a65e98295ec2/android/src/main/java/com/gantix/JailMonkey/JailMonkeyModule.java#L94).

I've tested this on a fresh out-of-the-box Vernee Thor running Android 7.0 by logging the boolean results of each of the three methods. Only method 1 returned `true`. The rest returned `false`. I checked the result of `android.os.Build.TAGS` and it returns `'test-keys'`. Running `cat /system/build.prop | grep ro.build.tags` via `adb shell` returns the same.

I tried running `su` via `adb shell` but the binary is not installed so my assumption is this device is not rooted.

Apparently in this case, the `'test-keys'` build tag doesn't necessarily mean the device is rooted but rather the OS image was not appropriately signed. [Here](https://source.android.com/devices/tech/ota/sign_builds) and [here](https://android.stackexchange.com/questions/176083/does-test-keys-mean-device-is-rooted) is some more info on that.

@GantMan Should this root detection method be used if it doesn't necessarily indicate a rooted device? I'm unsure, since [this](https://github.com/scottyab/rootbeer) library also uses the test-keys method.

**Comment by GantMan** [comment]
Hrmmmmmm....   I don't think false positives should be allowed.  It's far more destructive.  Maybe at some point, we can do a "possible root" but for now, it should not fail like that.  Would you like to PR the removal of the offending check?

**Comment by gustavjf** [comment]
I'd be happy to!

**Comment by GantMan** [comment]
merged your code and bumped to version 0.1.0 - Thanks!

@gustavjf - interested in becoming a core contributor?   I don't want to hold you back when your project calls for updates.

**Comment by gustavjf** [comment]
Much appreciated, thank you!

One thing I felt I should point out: I'm not sure how you're doing your versioning, but wouldn't this change be considered a breaking one according to semver? If anyone relying on the test keys check upgrades to the new minor version 0.1.0, it might be an unexpected surprise for them.

Thank you for the core contributor offer, but at the moment I don't find it necessary. Perhaps when I've contributed a few more PRs I can reconsider :)
