### ISSUE TITLE
Jump to version 0.2.1

### ISSUE THREAD

**Issue by fjtrujy** [GantMan/jail-monkey#24]
Hello,
After the PR that you merged yesterday #23 , could you kindly jump to a new version and publish it into NPM environment?

Thanks

**Comment by Nachox07** [comment]
Also waiting for this.

**Comment by GantMan** [comment]
Actually I want to leave the semversion subset madness.  I jumped to version 1.0.0 

It's time!

Let me know how 1.0.0 works out!

**Comment by fjtrujy** [comment]
Thanks @GantMan for you quick response, but I think that you have forgotten to update the version inside the `package.json`. This one still shows the `0.2.0`

Thanks in advance.

**Comment by GantMan** [comment]
The tool I use seems to have skipped that step.  Updated manually.

Please let me know how well it works!  Still working on getting that phone from a friend to test again.
