### ISSUE TITLE
Execution failed for task ':jail-monkey:verifyReleaseResources'.

### ISSUE THREAD

**Issue by lucasfonmiranda** [GantMan/jail-monkey#28]
Hi,
I have this problem when i try to create one apk release with the jaik-monkey library.
After using:
```
cd android && ./gradlew assembleRelease

```
This exceptions appear:

```
* What went wrong:
Execution failed for task ':jail-monkey:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt
```
package.json
```
 "jail-monkey": "^1.0.0",
"react-native": "0.57.1"
```

**Comment by nandofer126** [comment]
Hello, I use a Ubuntu 18 LTS, running this comand worked for me: **sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386**
I needed some libraries, after that, its compile correctly.

**Comment by TareqElMasri** [comment]
@nandofer126 So, how can I do that in MacOS?

**Comment by lucasmirandadev** [comment]
It's the same problem here, i use MacOS for developer and need to know how can i do that?

**Comment by bharadwajsampath** [comment]
@GantMan The error is because of 

> No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

Will try if I can fix something quickly and raise a PR for it

**Comment by GantMan** [comment]
awesome!  Looking forward to it

**Comment by MoDevby** [comment]
I don't think it's related to the RN version, it's more on the Android side.
for me this was solved by updating the compileSdkVersion and buildToolsVersion.
I will send a PR, but i am not sure if this is a working solution for everyone.

**Comment by ravimini** [comment]
updating the compileSdkVersion and buildToolsVersion. not working.

**Comment by pt7892** [comment]
Adding this to my root build.gradle fixed it for me
`subprojects { subproject ->
    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}`
