### ISSUE TITLE
Community contributions

### ISSUE THREAD

**Issue by kmye** [GantMan/jail-monkey#296]
Hello, not sure is this a good to place to mention this.

Is there any workflows for contributions from the community? I recently made a PR and it was merged (thats great, thanks a lot) but I also needed the version to be bumped so that i can actually pull the changes into my project.

I have noticed people are forking this repository to maintain a newer version, wouldn't it better to just keep this repo and update the version regularly when people has new fixes to this repository? 

I think what is lacking here is maybe a readme on how to contribute to this repository. Would be great for repository owner to let us know how we can help!

**Comment by GantMan** [comment]
Would you like to be an editor to the repo and the npm?  
Just give me your npm name and I'll get you access.

I'm not currently using the library so it's hard for me to maintain.

**Comment by GantMan** [comment]
Welcome to the club!
<img width="758" alt="Screenshot 2024-12-02 at 8 18 23 AM" src="https://github.com/user-attachments/assets/3065727a-e074-4857-8ac3-65fd8c66e619">

Just need your npm

**Comment by kmye** [comment]
okay, my npm name is `kmye90`

**Comment by GantMan** [comment]
done!

**Comment by kmye** [comment]
> done!

thanks!
