### ISSUE TITLE
Package is giving issue while creating android builds

### ISSUE THREAD

**Issue by FlowerbeanAnsh** [GantMan/jail-monkey#306]
After recent publish the package is giving below mentioned error while creating android build, earlier it was totally working fine.
Using react-native v0.64

error: package undefined does not exist
import undefined.JailMonkeyPackage;
                ^

error: cannot find symbol
      new JailMonkeyPackage(),
          ^
  symbol:   class JailMonkeyPackage
  location: class PackageList
2 errors

FAILURE: Build failed with an exception.

**Comment by kmye** [comment]
Hi, do you have a repo setup to replicate this issue? thanks!

**Comment by ImKifu** [comment]
The error indicates that there is an issue with the AndroidManifest.xml file in the jail-monkey module. Specifically, it mentions that no package name was found. 

To resolve this issue, you need to ensure that the AndroidManifest.xml file in the jail-monkey module has a valid package name. 

1. Open the AndroidManifest.xml file located at node_modules/jail-monkey/android/src/main/AndroidManifest.xml.
2. Ensure that the package attribute is correctly defined in the <manifest> tag. It should look something like this:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.gantix.JailMonkey">
    <!-- Other configurations -->
</manifest>
```
Save the file and try to clean and rebuild your project again:

```
cd android
./gradlew clean
cd ..
npx react-native run-android
```

or u can use older version such as 2.8.0
package.json:
`"jail-monkey": "2.8.0",`

**Comment by kmye** [comment]
Hello @FlowerbeanAnsh,

Ever since [PR#232](https://github.com/GantMan/jail-monkey/pull/232) we no longer support AGP < 7.

It is recommended to upgrade your react native and packages to the latest version as older versions of react native dependencies may contain security vulnerability
