### ISSUE TITLE
Xcode build error

### ISSUE THREAD

**Issue by TheKuyPeD** [GantMan/jail-monkey#31]
I already linked the library. When I build in xcode got this error

> ld: warning: directory not found for option '-L/Users/user/Library/Developer/Xcode/DerivedData/project-name/Build/Products/Debug-iphonesimulator/React'

> duplicate symbol _OBJC_CLASS_$_JailMonkey in:
>     /Users/user/Library/Developer/Xcode/DerivedData/project-name/Build/Products/Debug-iphonesimulator/jail-monkey/libjail-monkey.a(JailMonkey.o)
>     /Users/user/Library/Developer/Xcode/DerivedData/project-name/Build/Products/Debug-iphonesimulator/libJailMonkey.a(JailMonkey.o)

> duplicate symbol _OBJC_METACLASS_$_JailMonkey in:
>     /Users/user/Library/Developer/Xcode/DerivedData/project-name/Build/Products/Debug-iphonesimulator/jail-monkey/libjail-monkey.a(JailMonkey.o)
>     /Users/user/Library/Developer/Xcode/DerivedData/project-name/Build/Products/Debug-iphonesimulator/libJailMonkey.a(JailMonkey.o)

> ld: 2 duplicate symbols for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by murari85b7** [comment]
Select the project target then go to the build phases->Link binary with libraries
inside Link binary with libraries check it may be added twice **'libJailMonkey.a'**. Remove it one of them. It will work.
