### ISSUE TITLE
isJailBroken() -- A problem with ios?

### ISSUE THREAD

**Issue by Don-oneself** [GantMan/jail-monkey#41]
jail-monkey v:2.1.1
ios :12.1.4  testfight    
method: 
JailMonkey.isJailBroken() = true 
is this right ?

**Comment by PavanKumar-sa** [comment]
React Native 0.60.3 JailMonkey.isJailBroken() returns null and not working.

**Comment by vaishnavtn** [comment]
Same issue here. 
React Native 0.61.5 JailMonkey.isJailBroken() returns null and not working.

**Comment by levibuzolic** [comment]
This doesn't sound correct, please run the [example app](https://github.com/GantMan/jail-monkey/tree/master/ExampleProject) and post what results you get. Also, it's important to know what version of JailMonkey you're running.

`isJailBroken` returning `null` is likely a sign that the native code may not have been installed/linked correctly.

![Simulator Screen Shot - iPhone 8 - 2021-06-24 at 10 38 45](https://user-images.githubusercontent.com/721323/123185419-3fe69580-d4d9-11eb-9d3a-17b6e22efb31.png)

**Comment by vaishnavtn** [comment]
React-Native - 0.61.5
jail-monkey@2.3.0


Getting error in `JailMonkey.m` on `line no 265` as `Property 'isiOSOnMac' not found on object of type 'NSProcessInfo'`

if (@available(iOS 14.0, *)) {
        isiOSAppOnMac = [NSProcessInfo processInfo].isiOSAppOnMac; `// line no 265 `
}

**Comment by levibuzolic** [comment]
@vaishnavtn would you be able to try with the updated native code at https://github.com/GantMan/jail-monkey/pull/98 and see if that resolves the issue?

**Comment by vaishnavtn** [comment]
Yes, it's working now with that change. But it's returning `false` if I run app on simulator.

**Comment by levibuzolic** [comment]
@vaishnavtn `false` is expected on the simulator. 

I can merge and release this later today.

**Comment by levibuzolic** [comment]
@vaishnavtn I've made a new release, let me know how it goes.

**Comment by vaishnavtn** [comment]
It's working. Thanks!
