### ISSUE TITLE
Create and publish a release

### ISSUE THREAD

**Issue by GabrielePrestifilippo** [GantMan/jail-monkey#50]
I noticed the last release was made a while ago (05/04). And since then, many fixes were merged, in particular, #46 and #49 which solve some building problems for Android.

Would it be possible to create and publish a new release? Is there a procedure or a schedule this project follows?

**Comment by GantMan** [comment]
Yup.  Just wondering.  Would you be interested in being a contributor?  That way you could merge/release?
