### ISSUE TITLE
False alarm on brand new Samsung Galaxy Note10+

### ISSUE THREAD

**Issue by kasperwandahl** [GantMan/jail-monkey#58]
Hi

We have gotten a bug report from one of our customers. He has just bought a brand new phone straight from the electronics store (he peeled plastic of himself). When he installed our app that uses this package, he got the error that his phone is rooted, even though it's not.

I have these images of software versions on the phone (sorry about the glare):
![image](https://user-images.githubusercontent.com/6974100/70789596-97a82a80-1d93-11ea-8be5-621a5c61054d.png)
![image](https://user-images.githubusercontent.com/6974100/70789623-a68edd00-1d93-11ea-8c90-57007dd8b04c.png)

**Comment by GantMan** [comment]
hiya!   I nolonger have the devices to test this package.  I'd be happy to merge any pull request that identifies the bug, but as far as tracking down bugs, I'm unable.

I leave the package available on GitHub as a resource and to merge pull-requests that come in.

This project needs a maintainer.

**Comment by kasperwandahl** [comment]
Hey @GantMan .. Thanks for getting back to me. This is a customers device, so I would have to get one in order to test :) I'll just close this issue for now.

**Comment by unicornRainbows** [comment]
I have the same issue for:

Samsung Galaxy S8 
and
Samsung A7

and I have checked by installing the play store apps which check if the device is rooted and it is not.

Could someone point me in the right direction, I am happy to create a PR but don't know where to start.

👍

**Comment by quantumarun** [comment]
Got Reported it on "Samsung Galaxy Note 20 Ultra 5G". Any clue or suggestion how to get around it. I might be happy to look around and contribute if you can guide around. As for device even i don't have that.

**Comment by akshgods** [comment]
Got same issue on note 10+ , other are working perfectly.
device is not rooted , new one customer got this issue

**Comment by jordanjoecooper** [comment]
@unicornRainbows & @akshgods If you run [this app](https://play.google.com/store/apps/details?id=com.scottyab.rootbeer.sample&hl=en_GB&gl=US) does is also say root detected and if so what flags up?

**Comment by RohitPatilAtShell** [comment]
I am also getting this issue in one of my client device:
Brand: Samsung
OS: Lineageos-18 
Android: 11

I have already tested that the device is not rooted(attached screenshot).
Its a false alarm!!!

Please help me to get this issue resoled.
Thanks in advance.


![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/92922605/202458726-6d8315fa-78a7-41b9-a88c-625e6c009540.png)
