### ISSUE TITLE
isDebuggedMode is not a function.

### ISSUE THREAD

**Issue by Knjaz89** [GantMan/jail-monkey#64]
isDebuggedMode is not a function.
v 2.3.2

**Comment by XELoh** [comment]
same, I only can use **isJailBroken()** other showing is not a function

**Comment by Schabaani** [comment]
Same issue (**isDebugged is not a function**). I use:

```
JailMonkey.isDebuggedMode().then(res => {
	console.warn('res: ', res);
});
```

**Comment by lucasrocha7111** [comment]
Same here.

**Comment by pavel-corsaghin** [comment]
I faced the same issue. Resolved by using __DEV__ flag from react-native
