### ISSUE TITLE
Getting a false positive on iOS 10

### ISSUE THREAD

**Issue by GantMan** [GantMan/jail-monkey#7]
need to update and work properly with iOS 10

**Comment by aprct** [comment]
@GantMan Yo! Any luck with this issue? I've confirmed that two of my coworkers are getting this issue on devices that were previously jailbroken, but aren't anymore.

**Comment by GantMan** [comment]
I have a fix for detecting Android mock locations on the Marshmellow, and will revisit this one soon.  If you can find the correct obj-c I'll do it.

**Comment by aprct** [comment]
Getting false positives on Android now too :(

**Comment by GantMan** [comment]
Ah yes, fortunately my PR to facebook react-native was accepted.  It seems I'll need to nearly rewrite this entire component.

Can you provide your Android versions and any hardware specs that will help?  I'll try to get to this soon.  Super busy time of the year :(

**Comment by aprct** [comment]
Nexus 6P running Android 6.0.1

Can I help in any way? Let me know what needs to be done!

**Comment by GantMan** [comment]
any reliable native code that can detect jailbroken on iOS and Android with these versions would be ideal.  Links are perfect.

**Comment by aprct** [comment]
https://github.com/beast/react-native-isDeviceRooted for both Android and iOS.

**Comment by aprct** [comment]
Re: Android

I've looked into it some more and it looks like these 2 things are returning true, which causes the freakout:

- `canExecuteCommand("/system/bin/which su")` 
- `canExecuteCommand("which su")`

I've refactored a bit and submitted a PR. Should fix false positives for Android devices.
