### ISSUE TITLE
Cannot read property 'isJailBroken' of null in Android

### ISSUE THREAD

**Issue by vinegarpusit** [GantMan/jail-monkey#81]
JailMonkey works fine in IOS but when I run it with an android emulator I always get this error.

Also when I use other API such as `isDebuggedMode()`, `trustFall()`, etc... I always get the same error:

`Cannot read property 'isDebuggedMode' of null` etc.

![Screen Shot 2021-02-05 at 11 18 23 AM](https://user-images.githubusercontent.com/39085037/106985597-bb52df00-67a4-11eb-8b04-6e5ce5180ca0.png)

**Comment by levibuzolic** [comment]
@vinegarpusit have you correctly linked the native modules and rebuilt your Android app? This would usually point to the native library not being present.

**Comment by vinegarpusit** [comment]
> @vinegarpusit have you correctly linked the native modules and rebuilt your Android app? This would usually point to the native library not being present.

Thanks for bringing that up. I solved it by linking the package to android. `npx react-native link jail-monkey --platforms android`

This is kinda weird because on my other project this doesn't show up even If I didn't link the package to android.
